<a href="https://colab.research.google.com/github/Fasguy16-coder/Fasguy16-coder/blob/main/Copy_of_c0754453_8d31_4e45_bed0_4e5a059f67b1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def customperm(a, b, c):
    # Generate a random uniform matrix of shape (a, b) with values in [0, c)
    uniform_matrix = np.random.uniform(low=0, high=c, size=(a, b))

    # Convert to integers (floor) to get discrete values in [0, c-1]
    int_matrix = np.floor(uniform_matrix).astype(int)

    # Generate random permutations for each row
    perm_matrix = np.array([np.random.permutation(row) for row in int_matrix])

    return perm_matrix

# Test the function
result = customperm(3, 4, 20)
print(result)

[[ 5 12  3  8]
 [19  0 14  7]
 [ 2 11  9 15]]